Repository yuyayaya/PAMER, pull requests merged in 2019-03, with the labels that each got.

#14 Add user function
  app/assets/stylesheets/custom.scss
  app/controllers/application_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/users/_user.html.erb
  app/views/users/index.html.erb
  app/views/users/profile_edit.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20190215101928_add_some_fields_to_users.rb
  db/schema.rb
Labels: IshiiYuya

#15 prepare heroku deproy
  Procfile
  config/environments/production.rb
  config/puma.rb
Labels: IshiiYuya

#16 Add heroku setting preparation
  config/environments/production.rb
Labels: IshiiYuya

#18 heroku preparation
  config/environments/production.rb
Labels: IshiiYuya

#19 make plan
  Gemfile
  Gemfile.lock
  app/controllers/plans_controller.rb
  app/models/plan.rb
  app/uploaders/image_uploader.rb
  app/views/plans/index.html.erb
  app/views/plans/new.html.erb
  db/migrate/20190302115432_add_name_to_plans.rb
  db/schema.rb
  db/seeds.rb
Labels: suzuki hiroto

#21 make request function
  app/assets/javascripts/requests.coffee
  app/assets/stylesheets/requests.scss
  app/controllers/requests_controller.rb
  app/helpers/requests_helper.rb
  app/models/request.rb
  app/models/user.rb
  app/views/plans/show.html.erb
  app/views/requests/new.html.erb
  config/routes.rb
  db/migrate/20190316080101_create_requests.rb
  db/schema.rb
  db/seeds.rb
  public/uploads/plan/image/1/img19.jpg
  public/uploads/plan/image/1/thumb_img19.jpg
  public/uploads/plan/image/1/thumb_名刺写真候補.jpg
  public/uploads/plan/image/1/名刺写真候補.jpg
  public/uploads/plan/image/2/thumb_名刺写真候補.jpg
  public/uploads/plan/image/2/名刺写真候補.jpg
  public/uploads/tmp/1552984731-14562-0001-6839/thumb_名刺写真候補.jpg
  public/uploads/tmp/1552984731-14562-0001-6839/名刺写真候補.jpg
  public/uploads/tmp/1553156306-4415-0001-1898/thumb_名刺写真候補.jpg
  public/uploads/tmp/1553156306-4415-0001-1898/名刺写真候補.jpg
  public/uploads/tmp/1553156344-4415-0002-6538/thumb_名刺写真候補.jpg
  public/uploads/tmp/1553156344-4415-0002-6538/名刺写真候補.jpg
  public/uploads/tmp/1553156381-4415-0003-1531/thumb_名刺写真候補.jpg
  public/uploads/tmp/1553156381-4415-0003-1531/名刺写真候補.jpg
  public/uploads/user/picture/52/thumb_名刺写真候補.jpg
  public/uploads/user/picture/52/名刺写真候補.jpg
  public/uploads/user/picture/53/thumb_名刺写真候補.jpg
  public/uploads/user/picture/53/名刺写真候補.jpg
  test/controllers/requests_controller_test.rb
  test/fixtures/requests.yml
  test/models/request_test.rb
Labels: suzuki hiroto

#24 mailer
  app/controllers/requests_controller.rb
  app/mailers/application_approval_mailer.rb
  app/views/application_approval_mailer/send_confirm_to_user.html.erb
  app/views/application_approval_mailer/send_confirm_to_user.text.erb
  config/environments/development.rb
  config/routes.rb
  test/mailers/application_approval_mailer_test.rb
  test/mailers/previews/application_approval_mailer_preview.rb
Labels: IshiiYuya, suzuki hiroto
