Repository yuyayaya/PAMER, pull requests merged in 2019-02, with the labels that each got.

#2 edit readme
  README.md
Labels: suzuki hiroto

#3 Finish static pages
  Gemfile
  Gemfile.lock
  app/assets/javascripts/static_pages.coffee
  app/assets/stylesheets/static_pages.scss
  app/controllers/static_pages_controller.rb
  app/helpers/static_pages_helper.rb
  app/views/layouts/application.html.erb
  app/views/static_pages/about.html.erb
  app/views/static_pages/contact.html.erb
  app/views/static_pages/help.html.erb
  app/views/static_pages/home.html.erb
  config/routes.rb
  test/controllers/static_pages_controller_test.rb
Labels: suzuki hiroto

#4 Add Bootstrap4
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/static_pages/home.html.erb
  test/controllers/static_pages_controller_test.rb
Labels: suzuki hiroto

#5 Add layout
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/static_pages.scss
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_rails_default.html.erb
  app/views/layouts/_shim.html.erb
  app/views/layouts/application.html.erb
  app/views/static_pages/home.html.erb
  config/routes.rb
  npm-debug.log
  test/controllers/static_pages_controller_test.rb
Labels: IshiiYuya

#6 Make a basic User model (including secure passwords)
  Gemfile
  Gemfile.lock
  app/assets/images/PAM.png
  app/assets/javascripts/users.coffee
  app/assets/stylesheets/users.scss
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/static_pages/home.html.erb
  app/views/users/new.html.erb
  config/routes.rb
  db/migrate/20190211052254_create_users.rb
  db/migrate/20190211090320_add_index_to_users_email.rb
  db/migrate/20190211090933_add_password_digest_to_users.rb
  db/schema.rb
  test/controllers/users_controller_test.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: suzuki hiroto

#7 make logo
  app/views/layouts/_header.html.erb
Labels: suzuki hiroto

#8 Add login logout function
  app/assets/javascripts/sessions.coffee
  app/assets/stylesheets/sessions.scss
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/sessions/new.html.erb
  config/routes.rb
  test/controllers/sessions_controller_test.rb
Labels: IshiiYuya

#9 sign-up
  app/assets/stylesheets/custom.scss
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_error_messages.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: suzuki hiroto

#10 add remember me
  app/assets/stylesheets/custom.scss
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  app/views/sessions/new.html.erb
  db/migrate/20190211222853_add_remember_digest_to_users.rb
  db/schema.rb
Labels: suzuki hiroto

#12 make plan pages
  Gemfile
  Gemfile.lock
  app/assets/javascripts/plans.coffee
  app/assets/stylesheets/plans.scss
  app/controllers/plans_controller.rb
  app/controllers/users_controller.rb
  app/helpers/plans_helper.rb
  app/models/plan.rb
  app/models/user.rb
  app/views/plans/_plan.html.erb
  app/views/plans/edit.html.erb
  app/views/plans/index.html.erb
  app/views/plans/new.html.erb
  app/views/plans/show.html.erb
  config/routes.rb
  db/migrate/20190213152903_create_plans.rb
  db/migrate/20190223073125_add__tag_to_plans.rb
  db/migrate/20190223092149_add_image_to_plans.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/plans_controller_test.rb
  test/fixtures/plans.yml
  test/models/plan_test.rb
Labels: suzuki hiroto

#13 add devise function
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/images/flogo_RGB_HEX-114.png
  app/assets/javascripts/users/omniauth_callbacks.coffee
  app/assets/stylesheets/users.scss
  app/assets/stylesheets/users/omniauth_callbacks.scss
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/helpers/devise_helper.rb
  app/helpers/sessions_helper.rb
  app/helpers/users/omniauth_callbacks_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/registrations/profile_edit.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/sessions/new.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/locales/devise.ja.yml
  config/routes.rb
  db/migrate/20190211052254_create_users.rb
  db/migrate/20190211090320_add_index_to_users_email.rb
  db/migrate/20190211090933_add_password_digest_to_users.rb
  db/migrate/20190211222853_add_remember_digest_to_users.rb
  db/migrate/20190212122930_devise_create_users.rb
  db/migrate/20190212124356_add_fields_to_user.rb
  db/migrate/20190215101928_add_some_fields_to_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/users/omniauth_callbacks_controller_test.rb
Labels: IshiiYuya, suzuki hiroto
